<?php

namespace hpsynapse\moduser\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;

use App\Facades\Tenant;

use hpsynapse\moduser\Facades\RoleRepo;
use hpsynapse\moduser\Facades\UserSystemRepo;
use hpsynapse\moduser\Models\User;
use hpsynapse\moduser\Models\UserRole;

/**
 * generate dashboard.js di MainApp berisis load seluruh komponen
 * dashboard se aplikasi ini. Harus dieksekusi setelah _dashboard.json tergenerate
 */
class GenerateDashboardJs extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'moduser:generateDashboardJs';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Generate dashboard.js dari config _dashboard.json';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        ini_set('memory_limit','1024M');
        set_time_limit(0);

        define('DS',DIRECTORY_SEPARATOR);
        
        $this->info('Command starting...');

        $string = [
            "// DO NOT EDIT MANUALY UNLESS YOU KNOW WHAT YOU ARE DOING \n",
            "// This files is autogenerated on command moduser:generateDashboardJs \n",
            "// containt list all dashboar and dashboard feature component \n\n",
            "export default {\n",
            "    template: {\n",
        ];        

        foreach (config('AppConfig.dashboard.template',[]) as $templateCode => $value) {
            $filePath = './../../../../'.$value['path'].'/dashboard/'.$templateCode.'.vue';
            $string[] = "        ".$templateCode.": resolve => {\n";
            $string[] = '            require.ensure(["'.$filePath.'"], () => {'. "\n";
            $string[] = '                resolve(require("'.$filePath.'"));'. "\n";
            $string[] = "            });\n";
            $string[] = "        },\n";
        };

        $string[] = "    },\n";
        $string[] = "    feature: {\n";
        
        foreach (config('AppConfig.dashboard.feature',[]) as $featurePermodule) {
            foreach($featurePermodule['feature'] as $featureCode => $value){
                $filePath = './../../../../'.$featurePermodule['path'].'/dashboard/feature/'.$featureCode.'.vue';
                $string[] = "        ".$featureCode.": resolve => {\n";
                $string[] = '            require.ensure(["'.$filePath.'"], () => {'. "\n";
                $string[] = '                resolve(require("'.$filePath.'"));'. "\n";
                $string[] = "            });\n";
                $string[] = "        },\n";
            }
        };

        $string[] = "    }\n";
        $string[] = "};";

        file_put_contents(
            base_path('app'.DS.'MainApp'.DS.'resources'.DS.'js'.DS.'dashboard.js'),
            implode('', $string)
        );

        $this->info('dashboard.js Generated successfully !');
    }
}
